### PR TITLE
Add Rust tools to RDF-LAMP stack

### PR DESCRIPTION
**Pull request by KonradHoeffner**
Rust has good support for basic RDF operations like querying, loading and serializing. With its focus on performance and safety at the same time and modern tooling, the programming language is a great fit for the kind of Semantic Web applications we need.
However there are weak points as well: There is no complete HDT support yet and libraries are often still under heavy development.

### CODE REVIEW

**Comment by dbooth-boston** [comment]
Should this section be called "Rust libraries" instead of "Rust tools", in accordance with your other suggestion?

**Comment by KonradHoeffner** [comment]
Yes that would be great! I didn't know if this would be approved so I didn't change it there yet.

**Comment by KonradHoeffner** [comment]
OK, I changed it.

**Comment by pchampin** [comment]
Great idea, and thanks for the credit ;)

FTR, Oxigraph is both a library *and* a tool (it can be used as a standalone triple-store and SPARQL endpoint)

**Pull request merged**
