### PR TITLE
Changes "average developers" to "most developers"  (drops 'mainstream')

### PR DESCRIPTION
**Pull request by dbooth-boston**
Per issue #79

### CODE REVIEW

**Review by TallTed — APPROVED** [review]

**Review by gkellogg — APPROVED** [review]

**Comment by udp** [comment]
This is much better.

**Comment by afs** [comment]
In the context of the text being changed, this is better.

**Review by pchampin — APPROVED** [review]

**Comment by udp** [comment]
Tagline still needs updating

**Comment by dbooth-boston** [comment]
> Tagline still needs updating

Fixed, thanks.

**Pull request merged**
